# Dockerfile.client
FROM node:20 as build

WORKDIR /app
COPY client/package*.json ./client/
RUN cd client && npm install

COPY client ./client
WORKDIR /app/client
RUN npm run build

# Serve with nginx
FROM nginx:alpine
COPY --from=build /app/client/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]